In [13]:
import MDAnalysis as mda
from MDAnalysis.analysis import distances as mda_distances
import numpy as np

In [2]:
ref = mda.Universe("cript_wt.pdb")

/Users/fabianbylehn/miniforge3/envs/atomicstrain/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:331: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using MDAnalysis.topology.guessers.
  warnings.warn("Element information is missing, elements attribute "


In [3]:
ca = ref.select_atoms("name CA")

In [4]:


distances = mda_distances.self_distance_array(ca.atoms.positions, box=None)

In [5]:
distances

array([3.80378185, 6.28331559, 9.15637889, ..., 3.79251903, 6.35961232,
       3.82691223])

In [6]:
len(distances)

7875

In [ ]:
def calculate_neighbors(positions, method, inner_radius=6.0, outer_radius=8.0):
    """
    Calculate the neighbors for each atom based on distance thresholds.
    
    Args:
        positions: Array of atom positions.
        method: Method to use for neighbor calculation ('cutoff', etc.)
        inner_radius: Inner distance threshold (optional for future use)
        outer_radius: Outer distance threshold to consider an atom as a neighbor.
    
    Returns:
        List of neighbor indices for each atom.
    """
    n_atoms = len(positions)
    neighbor_list = []

    # Use distance_array to get full n_atoms x n_atoms distance matrix
    distances = mda.analysis.distances.distance_array(positions, positions, box=None)

    if method == 'cutoff':
        for i in range(n_atoms):
            # Find neighbors within the outer radius, excluding self
            neighbors_mask = (distances[i] < outer_radius) & (distances[i] > 0)
            neighbor_indices = np.where(neighbors_mask)[0]
            if len(neighbor_indices) < 3:
                raise SystemExit(f"Too few neighbors for atom {i}, incrase the outer_radius")
            neighbor_list.append(neighbor_indices)
    
    return neighbor_list

In [36]:
neighbor_list = calculate_neighbors(ca.atoms.positions, 'cutoff')

too few neighbors for atom 0


In [15]:
neighbor_list

[array([1, 2]),
 array([0, 2, 3]),
 array([0, 1, 3, 4]),
 array([1, 2, 4, 5]),
 array([2, 3, 5, 6, 7, 8]),
 array([3, 4, 6, 7, 8]),
 array([  4,   5,   7,   8,   9, 112]),
 array([  4,   5,   6,   8,   9, 112]),
 array([  4,   5,   6,   7,   9,  10, 112]),
 array([  6,   7,   8,  10,  11, 111, 112, 113]),
 array([  8,   9,  11,  12,  95, 112, 113, 114]),
 array([ 9, 10, 12, 13, 95]),
 array([10, 11, 13, 14, 94, 95, 96]),
 array([11, 12, 14, 15, 94, 95]),
 array([12, 13, 15, 16, 92, 93, 94, 95]),
 array([13, 14, 16, 17, 92, 93, 94]),
 array([14, 15, 17, 18, 90, 91, 92, 93]),
 array([15, 16, 18, 19, 53, 55, 56, 90, 91, 92, 93]),
 array([16, 17, 19, 20, 53, 88, 89, 90, 91]),
 array([17, 18, 20, 21, 26, 49, 50, 53, 88, 89, 90, 91]),
 array([18, 19, 21, 22, 49, 87, 88, 89]),
 array([19, 20, 22, 23, 24, 25, 26, 49, 87, 88, 89]),
 array([20, 21, 23, 24, 86, 87, 88]),
 array([21, 22, 24, 25, 86, 87]),
 array([21, 22, 23, 25, 26]),
 array([ 21,  23,  24,  26,  27,  48,  49,  83, 125]),
 array([

In [29]:
neighbor_list[0]

array([1, 2])

In [32]:
len(neighbor_list[3])

4

In [34]:
for atom in range(len(neighbor_list)):
	if len(neighbor_list[atom]) < 3:
		print(f'too few neighbors for atom {atom}')

too few neighbors for atom 0
