In [1]:
import MDAnalysis as mda
from MDAnalysis.analysis import distances as mda_distances
import numpy as np

/home/fabian/mambaforge/envs/atomicstrain_kit/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
ref = mda.Universe("cript_wt.pdb")

/home/fabian/mambaforge/envs/mdanalysis/lib/python3.11/site-packages/MDAnalysis/topology/PDBParser.py:331: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using MDAnalysis.topology.guessers.
  warnings.warn("Element information is missing, elements attribute "


In [3]:
ca = ref.select_atoms("name CA")

In [5]:
distances

array([3.80378185, 6.28331559, 9.15637889, ..., 3.79251903, 6.35961232,
       3.82691223])

In [6]:
len(distances)

7875

In [37]:
def calculate_neighbors(positions, method, inner_radius=6.0, outer_radius=8.0):
    """
    Calculate the neighbors for each atom based on distance thresholds.
    
    Args:
        positions: Array of atom positions.
        method: Method to use for neighbor calculation ('cutoff', etc.)
        inner_radius: Inner distance threshold (optional for future use)
        outer_radius: Outer distance threshold to consider an atom as a neighbor.
    
    Returns:
        List of neighbor indices for each atom.
    """
    n_atoms = len(positions)
    neighbor_list = []

    # Use distance_array to get full n_atoms x n_atoms distance matrix
    distances = mda.analysis.distances.distance_array(positions, positions, box=None)

    if method == 'cutoff':
        for i in range(n_atoms):
            # Find neighbors within the outer radius, excluding self
            neighbors_mask = (distances[i] < outer_radius) & (distances[i] > 0)
            neighbor_indices = np.where(neighbors_mask)[0]
            if len(neighbor_indices) < 3:
                raise SystemExit(f"Too few neighbors for atom {i}, incrase the outer_radius")
            neighbor_list.append(neighbor_indices)
    
    return neighbor_list

In [38]:
neighbor_list = calculate_neighbors(ca.atoms.positions, 'cutoff')

SystemExit: Too few neighbors for atom 0, incrase the outer_radius

/Users/fabianbylehn/miniforge3/envs/atomicstrain/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [40]:
np.ones(len(neighbor_list))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [29]:
neighbor_list[0]

array([1, 2])

In [32]:
len(neighbor_list[3])

4

In [34]:
for atom in range(len(neighbor_list)):
	if len(neighbor_list[atom]) < 3:
		print(f'too few neighbors for atom {atom}')

too few neighbors for atom 0
